"use client";

import type { DynamicField } from "@/components/proposals/editor/section-fields";

export const COVER_APPEARANCE_FIELD_CONFIG: DynamicField[] = [
  {
    name: "backgroundImage",
    label: "Imagem de fundo",
    type: "image",
    group: "Aparência",
    visibleWhen: { field: "variant", notEquals: "minimal" },
  },
  {
    name: "coverHeight",
    label: "Altura da capa",
    type: "range",
    group: "Aparência",
    min: 100,
    max: 300,
    step: 5,
    numberMode: "int",
    unit: "%",
    helperText: "100% = altura atual, 300% = 3x a altura.",
  },
  { name: "backgroundColor", label: "Cor de fundo", type: "color", group: "Aparência" },
  { name: "overlayColor", label: "Cor do overlay", type: "color", group: "Aparência" },
  {
    name: "overlayOpacity",
    label: "Opacidade do overlay",
    type: "range",
    group: "Aparência",
    visibleWhen: { field: "overlayColor" },
    min: 0,
    max: 100,
    step: 1,
    numberMode: "int",
    unit: "%",
  },
  { name: "textColor", label: "Cor do texto", type: "color", group: "Aparência" },
  {
    name: "showSectionDivider",
    label: "Mostrar divisor abaixo da seção",
    type: "toggle",
    group: "Aparência",
  },
  {
    name: "alignment",
    label: "Alinhamento do conteúdo",
    type: "select",
    selectDisplay: "grid",
    group: "Aparência",
    options: [
      { label: "Topo esquerda", value: "top-left", icon: "grid-top-left" },
      { label: "Topo centro", value: "top-center", icon: "grid-top-center" },
      { label: "Topo direita", value: "top-right", icon: "grid-top-right" },
      { label: "Meio esquerda", value: "middle-left", icon: "grid-middle-left" },
      { label: "Meio centro", value: "middle-center", icon: "grid-middle-center" },
      { label: "Meio direita", value: "middle-right", icon: "grid-middle-right" },
      { label: "Base esquerda", value: "bottom-left", icon: "grid-bottom-left" },
      { label: "Base centro", value: "bottom-center", icon: "grid-bottom-center" },
      { label: "Base direita", value: "bottom-right", icon: "grid-bottom-right" },
    ],
  },
];

export const COVER_FIELD_CONFIG: DynamicField[] = [
  {
    name: "title",
    label: "Título",
    type: "text",
    group: "Conteúdo",
    editorMode: "compactRichText",
  },
  {
    name: "subtitle",
    label: "Descrição",
    type: "text",
    group: "Conteúdo",
    editorMode: "richText",
  },
  {
    name: "highlight",
    label: "Frase de Impacto",
    type: "text",
    group: "Conteúdo",
    helperText: "Texto curto para reforcar o valor principal da proposta.",
  },
  { name: "showCompanyName", label: "Exibir nome da empresa", type: "toggle", group: "Branding" },
  {
    name: "companyNamePlacement",
    label: "Posição do nome da empresa",
    type: "select",
    selectDisplay: "dropdown",
    group: "Branding",
    visibleWhen: { field: "showCompanyName", equals: true },
    options: [
      { label: "Topo do bloco", value: "header", icon: "ArrowUp" },
      { label: "Área de conteúdo", value: "content", icon: "Circle" },
      { label: "Rodapé da capa", value: "footer", icon: "ArrowDown" },
    ],
  },
  {
    name: "companyNameAlign",
    label: "Alinhamento do nome da empresa",
    type: "select",
    selectDisplay: "dropdown",
    group: "Branding",
    visibleWhen: { field: "showCompanyName", equals: true },
    options: [
      { label: "Esquerda", value: "left", icon: "AlignLeft" },
      { label: "Centro", value: "center", icon: "AlignCenter" },
      { label: "Direita", value: "right", icon: "AlignRight" },
    ],
  },
  { name: "showLogo", label: "Exibir logo da empresa", type: "toggle", group: "Branding" },
  {
    name: "logoPlacement",
    label: "Posição da logo",
    type: "select",
    selectDisplay: "dropdown",
    group: "Branding",
    visibleWhen: { field: "showLogo", equals: true },
    options: [
      { label: "Topo do bloco", value: "header", icon: "ArrowUp" },
      { label: "Área de conteúdo", value: "content", icon: "Circle" },
      { label: "Rodapé da capa", value: "footer", icon: "ArrowDown" },
    ],
  },
  {
    name: "logoAlign",
    label: "Alinhamento da logo",
    type: "select",
    selectDisplay: "dropdown",
    group: "Branding",
    visibleWhen: { field: "showLogo", equals: true },
    options: [
      { label: "Esquerda", value: "left", icon: "AlignLeft" },
      { label: "Centro", value: "center", icon: "AlignCenter" },
      { label: "Direita", value: "right", icon: "AlignRight" },
    ],
  },
  {
    name: "logoSize",
    label: "Tamanho da logo na capa",
    type: "range",
    group: "Branding",
    visibleWhen: { field: "showLogo", equals: true },
    min: 50,
    max: 200,
    step: 5,
    numberMode: "int",
    unit: "%",
    helperText: "100% = tamanho padrão (varia levemente entre topo, meio e rodapé).",
  },
  {
    name: "logo",
    label: "Logo",
    type: "image",
    group: "Branding",
    visibleWhen: { field: "showLogo", equals: true },
  },
  ...COVER_APPEARANCE_FIELD_CONFIG,
];

export const COVER_VARIANT_OPTIONS = [
  "hero-cinematic",
  "editorial-poster",
  "split-editorial",
  "glass-card",
  "data-hero",
] as const;
