"use client";

import type { SectionDefinition, SectionType } from "./types";

export const SECTION_DEFINITIONS: Record<SectionType, SectionDefinition> = {
  cover: {
    type: "cover",
    label: "Cover",
    icon: "🧢",
    category: "Essentials",
    variants: ["default", "split", "minimal"],
    defaultVariant: "default",
    fields: [
      { name: "backgroundImage", label: "Background image", type: "image" },
      { name: "overlayColor", label: "Overlay color", type: "color" },
      { name: "overlayOpacity", label: "Overlay opacity", type: "opacity" },
      { name: "title", label: "Title", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "showLogo", label: "Show logo", type: "toggle" },
    ],
    defaults: {
      title: "Solar Proposal",
      subtitle: "Built for {{nome_cliente}}",
      overlayColor: "#020617",
      overlayOpacity: 0.45,
      backgroundImage: "",
      showLogo: true,
    },
  },
  introduction: {
    type: "introduction",
    label: "Introduction",
    icon: "📝",
    category: "Essentials",
    variants: ["default", "story"],
    defaultVariant: "default",
    fields: [{ name: "text", label: "Rich text", type: "richtext" }],
    defaults: {
      text: "<p>Hello {{nome_cliente}}, this proposal was crafted for your project.</p>",
    },
  },
  about_company: {
    type: "about_company",
    label: "About Company",
    icon: "🏢",
    category: "Essentials",
    variants: ["default", "highlight"],
    defaultVariant: "default",
    fields: [
      { name: "text", label: "Text", type: "richtext" },
      { name: "image", label: "Image", type: "image" },
      { name: "years", label: "Years of experience", type: "number" },
      { name: "certifications", label: "Certifications", type: "multi_input" },
    ],
    defaults: {
      text: "<p>We are specialized in high-performance solar systems.</p>",
      years: 10,
      certifications: [],
    },
  },
  diagnostic_energy: {
    type: "diagnostic_energy",
    label: "Energy Diagnostic",
    icon: "⚡",
    category: "Financial",
    variants: ["topics", "list", "cards"],
    defaultVariant: "topics",
    fields: [
      { name: "monthlyBill", label: "Monthly bill", type: "number" },
      { name: "consumptionKwh", label: "Consumption (kWh)", type: "number" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "painPoints", label: "Pain points", type: "table", columns: ["text", "icon"] },
      { name: "impact", label: "Financial impact", type: "table", columns: ["text", "icon"] },
      { name: "highlightText", label: "Highlight", type: "text" },
    ],
    defaults: {
      monthlyBill: 650,
      consumptionKwh: 0,
      city: "",
      state: "",
      painPoints: [
        { text: "Aumento constante da conta", icon: "trending-up" },
        { text: "Dependência da concessionária", icon: "plug" },
      ],
      impact: [{ text: "Mais de R$ 48 mil gastos em 5 anos", icon: "dollar-sign" }],
      highlightText: "Cada mês sem decisão aumenta a perda financeira acumulada.",
    },
  },
  solution: {
    type: "solution",
    label: "Solution",
    icon: "💡",
    category: "Essentials",
    variants: ["topics", "cards"],
    defaultVariant: "topics",
    fields: [
      { name: "solutionName", label: "Title", type: "text" },
      { name: "text", label: "Description", type: "richtext" },
      { name: "benefits", label: "Benefits", type: "list" },
      { name: "howItWorks", label: "How it works", type: "text" },
    ],
    defaults: {
      solutionName: "Proposta alinhada ao seu contexto",
      text: "<p>Visão clara do que será entregue e do valor para o seu cenário — sem detalhes técnicos nesta seção.</p>",
      benefits: ["Clareza na decisão", "Foco em resultado", "Acompanhamento consultivo"],
      howItWorks: "",
    },
  },
  generation_consumption: {
    type: "generation_consumption",
    label: "Generation & consumption",
    icon: "📈",
    category: "Essentials",
    variants: ["default"],
    defaultVariant: "default",
    fields: [
      { name: "potencia", label: "System power (kWp)", type: "number" },
      { name: "geracaoMensal", label: "Monthly generation (kWh)", type: "number" },
      { name: "coberturaPercent", label: "Coverage (%)", type: "number" },
      { name: "text", label: "Intro", type: "richtext" },
    ],
    defaults: {
      potencia: 8,
      geracaoMensal: 872,
      coberturaPercent: 80,
      text: "<p>Monthly consumption vs production overview.</p>",
    },
  },
  proposal_equipment: {
    type: "proposal_equipment",
    label: "Proposal equipment",
    icon: "📦",
    category: "Essentials",
    variants: ["cards", "table", "list"],
    defaultVariant: "cards",
    fields: [
      { name: "sectionSubtitle", label: "Subtitle", type: "text" },
      { name: "text", label: "Introduction", type: "richtext" },
    ],
    defaults: {
      sectionSubtitle: "Components selected for your project",
      text: "<p>Main equipment included in this proposal.</p>",
    },
  },
  gallery: {
    type: "gallery",
    label: "Gallery",
    icon: "🖼️",
    category: "Visual",
    variants: ["grid_uniform", "masonry", "mosaic_hero", "editorial", "overlay"],
    defaultVariant: "grid_uniform",
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text" },
      { name: "title", label: "Title", type: "text" },
      { name: "countLabel", label: "Count label", type: "text" },
      {
        name: "items",
        label: "Items",
        type: "table",
        columns: ["title", "description", "photo"],
      },
    ],
    defaults: {
      eyebrow: "Portfólio",
      title: "Obras realizadas",
      countLabel: "projetos selecionados",
      items: [],
    },
  },
  economy_purchases: {
    type: "economy_purchases",
    label: "Purchase Power",
    icon: "🛍️",
    category: "Financial",
    variants: ["vertical_stack", "split", "inverted", "narrative"],
    defaultVariant: "vertical_stack",
    fields: [
      {
        name: "horizonYears",
        label: "Horizon (years)",
        type: "select",
        options: [
          { label: "5 years", value: "5" },
          { label: "10 years", value: "10" },
        ],
      },
      {
        name: "purchaseItems",
        label: "Purchase items",
        type: "table",
        columns: ["name", "unitPrice", "icon"],
      },
      { name: "text", label: "Rich text", type: "richtext" },
    ],
    defaults: {
      horizonYears: "10",
      text: "<p>Veja o potencial de compra com a economia estimada do projeto.</p>",
      purchaseItems: [
        { name: "iPhone 17", unitPrice: "8000", icon: "smartphone" },
        { name: "Carro popular", unitPrice: "78000", icon: "car" },
        { name: "Viagem internacional", unitPrice: "15000", icon: "plane" },
      ],
    },
  },
  pricing: {
    type: "pricing",
    label: "Pricing",
    icon: "📊",
    category: "Financial",
    variants: ["table", "compact"],
    defaultVariant: "table",
    fields: [
      { name: "items", label: "Items", type: "table", columns: ["item", "description", "value"] },
      { name: "total", label: "Total", type: "number" },
      { name: "discount", label: "Discount", type: "number" },
      { name: "paymentConditions", label: "Payment conditions", type: "text" },
    ],
    defaults: {
      items: [{ item: "Solar Kit", description: "Modules + inverter", value: "38900" }],
      total: 45300,
      discount: 0,
      paymentConditions: "30% upfront + 70% on completion",
    },
  },
  financing: {
    type: "financing",
    label: "Financing",
    icon: "🏦",
    category: "Financial",
    variants: ["default", "split"],
    defaultVariant: "default",
    fields: [
      { name: "monthlyInstallment", label: "Monthly installment", type: "number" },
      { name: "totalMonths", label: "Total months", type: "number" },
      { name: "currentBill", label: "Current bill", type: "number" },
    ],
    defaults: { monthlyInstallment: 520, totalMonths: 96, currentBill: 650 },
  },
  testimonials: {
    type: "testimonials",
    label: "Testimonials",
    icon: "⭐",
    category: "Trust",
    variants: ["overlap", "quote_header"],
    defaultVariant: "overlap",
    fields: [
      { name: "sectionEyebrow", label: "Eyebrow label", type: "text" },
      {
        name: "items",
        label: "Testimonials",
        type: "table",
        columns: ["name", "subtitle", "text", "photo"],
      },
    ],
    defaults: {
      sectionEyebrow: "Testimonials",
      items: [
        {
          name: "Marina Costa",
          subtitle: "Homeowner",
          text: "The process was smooth and the savings are real.",
          photo: "",
        },
      ],
    },
  },
  social_proof: {
    type: "social_proof",
    label: "Social Proof",
    icon: "📈",
    category: "Trust",
    variants: ["stats", "logos"],
    defaultVariant: "stats",
    fields: [{ name: "items", label: "Proof bullets", type: "list" }],
    defaults: { items: ["+500 installations", "4.9 average review", "Certified installers"] },
  },
  guarantees: {
    type: "guarantees",
    label: "Guarantees",
    icon: "🛡️",
    category: "Trust",
    variants: ["cards", "simple"],
    defaultVariant: "cards",
    fields: [{ name: "items", label: "Guarantees", type: "list" }],
    defaults: { items: ["25-year module performance", "10-year inverter warranty"] },
  },
  process_steps: {
    type: "process_steps",
    label: "Process Steps",
    icon: "🧭",
    category: "Essentials",
    variants: ["vertical", "horizontal", "cards"],
    defaultVariant: "vertical",
    fields: [
      {
        name: "items",
        label: "Steps",
        type: "table",
        columns: ["title", "description", "estimatedTime"],
      },
    ],
    defaults: {
      items: [
        {
          title: "Discovery",
          description: "Scope and feasibility review.",
          estimatedTime: "2 days",
        },
        {
          title: "Engineering",
          description: "Design and permits.",
          estimatedTime: "2 weeks",
        },
        {
          title: "Installation",
          description: "On-site build and commissioning.",
          estimatedTime: "3 days",
        },
      ],
    },
  },
  faq: {
    type: "faq",
    label: "FAQ",
    icon: "❓",
    category: "Trust",
    variants: ["list", "two_column", "interview", "headline"],
    defaultVariant: "list",
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text" },
      { name: "title", label: "Title", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "items", label: "FAQ items", type: "table", columns: ["question", "answer"] },
    ],
    defaults: {
      eyebrow: "Perguntas frequentes",
      title: "As principais dúvidas, respondidas.",
      subtitle: "",
      items: [],
    },
  },
  cta: {
    type: "cta",
    label: "Proposal response",
    icon: "🚀",
    category: "Essentials",
    variants: ["primary", "secondary"],
    defaultVariant: "primary",
    fields: [
      { name: "proposalUrl", label: "Proposal base URL", type: "url" },
      { name: "acceptEnabled", label: "Show accept", type: "toggle" },
      { name: "editEnabled", label: "Show request changes", type: "toggle" },
      { name: "rejectEnabled", label: "Show reject", type: "toggle" },
      { name: "dangerColor", label: "Reject accent color", type: "color" },
    ],
    defaults: {
      proposalUrl: "https://example.com/proposal",
      acceptEnabled: true,
      editEnabled: true,
      rejectEnabled: true,
      dangerColor: "",
    },
  },
  signature: {
    type: "signature",
    label: "Signature",
    icon: "✍️",
    category: "Advanced",
    variants: ["default", "digital"],
    defaultVariant: "default",
    fields: [
      { name: "signerName", label: "Signer name", type: "text" },
      { name: "signerTitle", label: "Signer title", type: "text" },
    ],
    defaults: { signerName: "Sales Executive", signerTitle: "Solar Consultant" },
  },
  comparison: {
    type: "comparison",
    label: "Comparison",
    icon: "⚖️",
    category: "Financial",
    variants: ["default", "highlight"],
    defaultVariant: "default",
    fields: [
      { name: "beforeValue", label: "Before value", type: "number" },
      { name: "afterValue", label: "After value", type: "number" },
    ],
    defaults: { beforeValue: 650, afterValue: 120 },
  },
  video: {
    type: "video",
    label: "Video",
    icon: "🎬",
    category: "Visual",
    variants: ["hero", "split", "cinematic", "dark", "editorial"],
    defaultVariant: "hero",
    fields: [
      { name: "videoUrl", label: "Video URL (YouTube/Vimeo)", type: "url" },
      { name: "eyebrow", label: "Highlight phrase", type: "text" },
      { name: "title", label: "Title", type: "text" },
      { name: "description", label: "Description", type: "richtext" },
    ],
    defaults: {
      videoUrl: "https://www.youtube.com/watch?v=KA_uZ9otOlc",
      eyebrow: "Veja em vídeo",
      title: "Como funciona uma instalação solar do início ao fim.",
      description:
        "<p>Um tour pela nossa equipe técnica em obra: do <strong>dimensionamento ao comissionamento</strong>.</p>",
    },
  },
  custom: {
    type: "custom",
    label: "Custom",
    icon: "🧩",
    category: "Advanced",
    variants: ["default"],
    defaultVariant: "default",
    fields: [{ name: "text", label: "Custom content", type: "richtext" }],
    defaults: { text: "<p>Custom conversion-focused section.</p>" },
  },
};

export const SECTION_TYPES = Object.keys(SECTION_DEFINITIONS) as SectionType[];
